// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Report.Infrastructure.Persistence;

namespace Report.Infrastructure.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20220110010100_SeederUpdated")]
    partial class SeederUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Report.Domain.Entities.Rapor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<Guid>("DurumId")
                        .HasColumnType("uuid")
                        .HasColumnName("durum_id");

                    b.Property<DateTime>("LastupDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastup_date");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("DurumId");

                    b.ToTable("raporlar");
                });

            modelBuilder.Entity("Report.Domain.Entities.RaporDurum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Durum")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("durum");

                    b.Property<DateTime>("LastupDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastup_date");

                    b.HasKey("Id");

                    b.ToTable("rapor_durumlar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54a0bfc0-d88d-4e75-a067-9547e977c926"),
                            CreateDate = new DateTime(2022, 1, 10, 4, 1, 0, 233, DateTimeKind.Local).AddTicks(8198),
                            Durum = "HAZIRLANIYOR",
                            LastupDate = new DateTime(2022, 1, 10, 4, 1, 0, 234, DateTimeKind.Local).AddTicks(7723)
                        },
                        new
                        {
                            Id = new Guid("2143a48a-7190-4ee0-a894-743733ac09b9"),
                            CreateDate = new DateTime(2022, 1, 10, 4, 1, 0, 234, DateTimeKind.Local).AddTicks(9654),
                            Durum = "TAMAMLANDI",
                            LastupDate = new DateTime(2022, 1, 10, 4, 1, 0, 234, DateTimeKind.Local).AddTicks(9661)
                        },
                        new
                        {
                            Id = new Guid("1563a48a-7190-4ee0-a894-743733ac09b9"),
                            CreateDate = new DateTime(2022, 1, 10, 4, 1, 0, 234, DateTimeKind.Local).AddTicks(9672),
                            Durum = "BİLİNMİYOR",
                            LastupDate = new DateTime(2022, 1, 10, 4, 1, 0, 234, DateTimeKind.Local).AddTicks(9673)
                        });
                });

            modelBuilder.Entity("Report.Domain.Entities.Rapor", b =>
                {
                    b.HasOne("Report.Domain.Entities.RaporDurum", "RaporDurum")
                        .WithMany("Raporlar")
                        .HasForeignKey("DurumId")
                        .HasConstraintName("Rapor_Rapor_Durum_Durum_Id_Foreign_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaporDurum");
                });

            modelBuilder.Entity("Report.Domain.Entities.RaporDurum", b =>
                {
                    b.Navigation("Raporlar");
                });
#pragma warning restore 612, 618
        }
    }
}
